(in-package :centi)

(defun print (thing &optional stream)
  (labels ((%princ (thing)
             (princ thing stream))
           (print-empty-list ()
             (%princ "()"))
           (print-list (o)
             (%princ "(")
             (print1 (pop o))
             (loop
               (cond ((consp o)
                      (%princ " ")
                      (print1 (pop o)))
                     ((null o)
                      (%princ ")")
                      (return))
                     (t
                      (%princ " . ")
                      (print1 o)
                      (%princ ")")
                      (return)))))
           (print-string (o)
             (%princ #\")
             (loop for c across o do (%princ c))
             (%princ #\"))
           (print-array (o)
             (%princ "[")
             (reduce (lambda (a e)
                       (when a (%princ " "))
                       (print1 e))
                     o
                     :initial-value nil)
             (%princ "]"))
           (print1 (o)
             (cond ((null o)       (print-empty-list))
                   ((consp o)      (print-list o))
                   ((stringp o)    (print-string o))
                   ((arrayp o)     (print-array o))
                   (t              (cl:princ o)))))
    (print1 thing)
    thing))
