(in-package :centi.printer)

(defun print1 (thing &optional stream)
  (labels ((%princ (thing)
             (princ thing stream))
           (print-empty-list (o)
             (%princ "()"))
           (print-list (o)
             (%princ "(")
             (print1 (pop o))
             (loop
               (cond ((consp o)
                      (%princ " ")
                      (print1 (pop o)))
                     ((null o)
                      (%princ ")")
                      (return))
                     (t
                      (%princ " . ")
                      (print1 o)
                      (%princ ")")
                      (return)))))
           (print-array (o)
             (case (array-element-type o)
               ((character base-char)
                (%princ #\")
                (loop for c across o do (%princ c))
                (%princ #\"))
               (t
                (%princ "[")
                (loop with first? = t
                      for e across o
                      do (if first?
                             (setq first? nil)
                             (%princ " "))
                         (print1 e))
                (%princ "]"))))
           (print-record (o)
             (let ((tag (r:get o 0)))
               (%princ "#<")
               (print1 tag)
               (%princ ">")))
           (print1 (o)
             (cond ((null o)         (print-empty-list o))
                   ((consp o)        (print-list o))
                   ((arrayp o)       (print-array o))
                   ((r:record? o)    (print-record o))
                   (t                (cl:princ o)))))
    (print1 thing)
    thing))

(defun print (thing &optional stream)
  (print1 thing stream)
  (terpri stream))
